### ISSUE TITLE
errormessage: "cranpacks nicht teil von rtutorials"

### ISSUE THREAD

**Issue by marie-kamp** [statistik-lehre/rtutorials#36]
**Beschreiben Sie den Fehler:**
die Methode ohne Internetverbindung mit cranpacks scheint nicht zu funktionieren, habe ich nun auskommentiert

**Zum Replizieren**
Schritte, um den Fehler zu erzeugen:
1. Tutorial-Name `01b_funktionen`
2. Kapitel `Pakete`
3. Unterüberschrift `Pakete`
4. Exercise-Codeblock namens `{r cran_packages_reading}.`

**Erwartetes Verhalten**
Eine klare Beschreibung dessen, wie es ohne Fehler sein sollte

**Betriebssytem**
-  Windows 10

**Comment by luk-brue** [comment]
ich kümmere mich darum @marie-kamp

**Comment by luk-brue** [comment]
Repariert, in dem ich cranpacks-Datensatz hinzugefügt habe (ist beim Umstellen unserer Branching-Strategie verloren gegangen). Commit #175f8d7 und folgende zwei
