### ISSUE TITLE
4b_vis Nach excersice ybarplot kann nicht mehr auf "weiter" geklickt werden

### ISSUE THREAD

**Issue by marie-kamp** [statistik-lehre/rtutorials#49]
**Beschreiben Sie den Fehler:**
Der weiter Button wird blockiert, da erst Übungen fertiggestellt werden sollen, auch wenn diese bereits ausgeführt wurden.

**Zum Replizieren**
Schritte, um den Fehler zu erzeugen:
1. Tutorial-Name `4b_vis`
2. Kapitel `Balkendiagramm`
3. Unterüberschrift `aesthetic mapping`
4. Exercise-Codeblock namens `ybarplot `

**Erwartetes Verhalten**
Nachdem die Übungen ausgefüllt wurden sollte es weiter im nächsten Kapitel gehen. Stattdessen wird darauf beharrt erst die Aufgaben zu verfollständigen, auch wenn dies passiert ist.

**Betriebssytem**
 Windows 10

**Comment by luk-brue** [comment]
Die Option im YAML-Header `allow_skip: false` verursacht dieses Verhalten. Gesa und ich hatten das extra so gesetzt, aber es wird dann tatsächlich erst möglich auf Weiter zu klicken, wenn alle Codeblöcke ausgeführt wurden. Also nicht nur die, wo Aufgaben drin sind, sondern auch die die einfach nur zur Anschauung dienen. 
Offensichtlich ist das verwirrend und auch ich find es relativ nervig beim späteren Anschauen, wenn nicht noch mal alles ausgefüllt werden muss. Deswegen sollten wir die Option vielleicht doch auf `true` setzen :)

**Comment by marie-kamp** [comment]
Ich find es eigentlich sehr gut diese Möglichkeit zu haben, dass die Studierenden da auch wirklich mitmachen, aber leider habe ich wirklich alles ausgeführt gehabt bis zu diesem Punkt. Evtl. gibt es da vielleicht ein Bug mit den offenen Fragen oder sowas, dass nicht erkannt wird, dass alles ausgeführt wurde 🤷‍♀️.
Ich habe es aber grade mal auf `true` gesetzt.
