### ISSUE TITLE
Boxplot Whiskers falsch beschrieben

### ISSUE THREAD

**Issue by luk-brue** [statistik-lehre/rtutorials#53]
**Stelle**
- Tutorial `4a_dispersion`
- Text direkt vor der Übersichtsgrafik Boxplot

**Was stimmt nicht?**
Da steht, die Whiskers gehen bis Median +/- 1.5 * IQR. Das ist aber nicht richtig.

**Wie wäre es inhaltlich richtig?**
Es müsste glaube ich heißen wie in der Zeile drüber. Q1 - 1.5*IQR, und Q3 + 1.5*IQR

**Comment by marie-kamp** [comment]
Bug fixed
